# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a74uszC51yW6GAoiohAyNeUj9wzz8kv2
"""

# Nama          : Ahmad Nayef Al Fito
# Email         : m180d4ky2784@bangkit.academy
# Id Dicoding   : fitooo

# Import Library
import streamlit as st
import pandas as pd
import plotly.express as px

# ==============================
# LOAD DATA
# ==============================

# Function to load data from a CSV file
@st.cache_resource
def load_data():
    # Load data from CSV file "hour.csv"
    hour_url = 'https://raw.githubusercontent.com/fitoooooo/Bangkit/main/hour.csv'
    data = pd.read_csv(hour_url)
    return data

# Load dataset
data = load_data()

# ==============================
# TITLE DASHBOARD
# ==============================
# Set page title
st.title("Bike Share Dashboard")

# ==============================
# SIDEBAR
# ==============================
# # Display sidebar information
st.sidebar.title("Informasi:")
st.sidebar.markdown("**• Nama: Ahmad Nayef Al Fito**")

st.sidebar.title("Dataset Bike Share")
# Show the dataset if selected in the sidebar
if st.sidebar.checkbox("Tampilkan Dataset"):
    st.subheader("Data Mentah")
    st.write(data)

# Display summary statistics if selected in the sidebar
if st.sidebar.checkbox("Tampilkan Statistik Ringkas"):
    st.subheader("Statistik Ringkas")
    st.write(data.describe())

# Show dataset source
st.sidebar.markdown("[Download Dataset](https://drive.google.com/file/d/1RaBmV6Q6FYWU4HWZs80Suqd7KQC34diQ/view?usp=sharing)")

st.sidebar.markdown('**Cuaca:**')
st.sidebar.markdown('1: Cerah, Awan Sedikit, Sebagian Cerah, Sebagian Cerah')
st.sidebar.markdown('2: Berkabut + Berawan, Berkabut + Awan Tersebar, Berkabut + Awan Sedikit, Berkabut')
st.sidebar.markdown('3: Hujan Ringan, Hujan Ringan + Badai Petir + Awan Tersebar, Hujan Ringan + Awan Tersebar')
st.sidebar.markdown('4: Hujan Lebat + Hujan Es + Badai Petir + Kabut, Salju + Kabut')

# create a layout with two columns
col1, col2 = st.columns(2)

with col1:
    # Season-wise bike share count
    # Mapping dari angka ke label musim
    season_mapping = {1: "spring", 2: "summer", 3: "fall", 4: "winter"}
    data["season_label"] = data["season"].map(season_mapping)

    season_count = data.groupby("season_label")["cnt"].sum().reset_index()
    fig_season_count = px.bar(season_count, x="season_label",
                              y="cnt", title="Jumlah Peminjaman Sepeda Berdasarkan Musim")
    st.plotly_chart(fig_season_count, use_container_width=True,
                    height=400, width=600)

with col2:
    # Weather situation-wise bike share count
    weather_count = data.groupby("weathersit")["cnt"].sum().reset_index()
    fig_weather_count = px.bar(weather_count, x="weathersit",
                               y="cnt", title="Jumlah Peminjaman Sepeda Berdasarkan Situasi Cuaca")
    st.plotly_chart(fig_weather_count, use_container_width=True,height=400, width=800)

# Hourly bike share count
hourly_count = data.groupby("hr")["cnt"].sum().reset_index()
fig_hourly_count = px.line(
    hourly_count, x="hr", y="cnt", title="Jumlah Peminjaman Sepeda Berdasarkan Jam")
st.plotly_chart(fig_hourly_count, use_container_width=True,
                height=400, width=600)

# Humidity vs. Bike Share Count
fig_humidity_chart = px.scatter(
    data, x="hum", y="cnt", title="Kelembaban vs. Jumlah Peminjaman Sepeda")
st.plotly_chart(fig_humidity_chart)

# Wind Speed vs. Bike Share Count
fig_wind_speed_chart = px.scatter(
    data, x="windspeed", y="cnt", title="Kecepatan Angin vs. Jumlah Peminjaman Sepeda")
st.plotly_chart(fig_wind_speed_chart)

# Temperature vs. Bike Share Count
fig_temp_chart = px.scatter(data, x="temp", y="cnt",
                            title="Suhu vs. Jumlah Peminjaman Sepeda")
st.plotly_chart(fig_temp_chart, use_container_width=True,
                height=400, width=800)
